local-storage:
  temporary-directory: 'docs'

kafka:
  bootstrap-server: '127.0.0.1:9092'
  chunk-processing-topic: 'chunks'

marqo:
  connection-string: 'http://127.0.0.1:8882'
  index-name: 'chunks'
  embedding-model: 'hf/e5-base-v2'
  insertion-batch-size: 10
  tensor-field: 'chunk'

postgres:
  host: '127.0.0.1'
  port: 5432
  username: 'postgres_user'
  password: 'secret_password'
  database: 'postgres'
  table: 'chunks'
  insertion-batch-size: 500

logging:
  level: 'INFO'